export const OVERVIEW = {
  FETCH: {
    REQUEST: 'OVERVIEW.FETCH.REQUEST',
    SUCCESS: 'OVERVIEW.FETCH.SUCCESS',
    ERROR: 'OVERVIEW.FETCH.ERROR'
  },
  ERROR: {
    CLEAR: 'OVERVIEW.ERROR.CLEAR'
  },
  CLEAR_STATE: 'OVERVIEW.CLEAR_STATE'
};
