export const WITHDRAWAL = {
  WITHDRAW_CASH: {
    REQUEST: 'WITHDRAWAL.WITHDRAW_CASH.REQUEST',
    SUCCESS: 'WITHDRAWAL.WITHDRAW_CASH.SUCCESS',
    FAILURE: 'WITHDRAWAL.WITHDRAW_CASH.FAILURE',
  },
};
